IfSome and ifNone return itself and other minor changes
peter-tackage/kotlin-options pull request #1
Opened 2017-06-04 14:00 UTC by tomaszpolanski

Additionally I was thinking if it was better not to have assert functions directly on option but exposed via test() like in Rx. How about it?

2017-06-04 14:39 UTC, peter-tackage commented
I'm not exactly sure about how the packaging is defined at the moment but ideally the test assertions module would be a separate dependency, meaning that it could be included via `testCompile` and not impact the core definition. So I don't think we need to have a `test()` on Option.

2017-06-05 06:22 UTC, tomaszpolanski commented
Fair enough :)

2017-06-05 09:23 UTC, peter-tackage requested changes

2017-06-05 09:23 UTC, peter-tackage commented on kotlin-options/src/test/kotlin/com/petertackage/kotlinoptions/OptionTest.kt
> +        val option =  optionOf(null)
Use `None` directly instead of `optionOf(null)`

```Kotlin
val result = None.ifNone { }
// then assert
```

2017-06-05 09:23 UTC, peter-tackage commented on kotlin-options/src/main/kotlin/com/petertackage/kotlinoptions/Option.kt
> +        if (this is Some && other is Some) {
This is probably simpler!

2017-06-05 09:23 UTC, peter-tackage commented on kotlin-options/src/main/kotlin/com/petertackage/kotlinoptions/Option.kt
> +        if (this is None) {
I know it's only one dimension to the solution, but is there a more idiomatic way of doing this? Perhaps something more consistent with the rest of the class? 

This what I could come up with:

```Kotlin

    fun ifSome(action: (T) -> Unit): Option<T> {
        return when (this) {
            is Some -> apply { action(value) }
            is None -> this
        }
    }

    fun ifNone(action: () -> Unit): Option<T> {
        return when (this) {
            is Some -> this
            is None -> apply { action() }
        }
    }
```

2017-06-05 16:03 UTC, peter-tackage approved these changes

2017-06-05 16:04 UTC, merged